# This file was generated by GoReleaser. DO NOT EDIT.
cask "tidefetch" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2a068763c13d6d6e62ec61370c03b1cbfeb9b0c38f675a5b7b847c881d65f001"
      url "https://github.com/Thre4dripper/tidefetch/releases/download/v#{version}/tidefetch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb6e8c360784e1bd0b8648909c7e3c56c003f5abada53715e9fd2311304e9c77"
      url "https://github.com/Thre4dripper/tidefetch/releases/download/v#{version}/tidefetch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ea8a8f16fa92993269d347e6853bb3e2d2a6bb8773f82bc2b83061206e853ae"
      url "https://github.com/Thre4dripper/tidefetch/releases/download/v#{version}/tidefetch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6130dbfa1348c25a80e0849599a8a259af5dfb6a21e9b889bc625c8eebe97fe8"
      url "https://github.com/Thre4dripper/tidefetch/releases/download/v#{version}/tidefetch_linux_arm64.tar.gz"
    end
  end

  name "tidefetch"
  desc "Terminal UI and self-hosted web UI for the aria2 download engine"
  homepage "https://github.com/Thre4dripper/tidefetch"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "aria2",
    ]

  binary "tidefetch"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/tidefetch"]
    end
  end

  # No zap stanza required

end
